UMP-20673-changes-for-kubernetes-higher-version
boldbi/boldbi-kubernetes pull request #36
Opened 2022-06-15 03:47 UTC by sivakumar-devops

2022-06-15 04:08 UTC, Vinoth-Krishnamoorthy requested changes
Revert changes that you made for testing and ensure only needed changes present

2022-06-15 04:08 UTC, Vinoth-Krishnamoorthy commented on deploy/ingress.yaml
> +  - #host: boldbi-devops-devtesting.boldbi.com
Revert unwanted static domain name mention

2022-06-15 04:11 UTC, sivakumar-devops commented on deploy/ingress.yaml
> +  - #host: boldbi-devops-devtesting.boldbi.com
concern addressed

2022-07-05 05:53 UTC, Vinoth-Krishnamoorthy approved these changes
Fine to proceed.

2022-07-05 05:53 UTC, merged